author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /TestExport_20220412
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.io/iiif/2/2qchts23_00000001.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 7100
    width: 9000
permalink: pretty
publication_info:
  date: '2022'
  editors: []
  title: "Insignium Rom\xE6 templorum prospectus exteriores interioresque: a celebrioribus\
    \ architectis inventi: nunc tandem suis cum plantis ac mensuris."
show_annotation_author: true
source_info:
  title: "Insignium Rom\xE6 templorum prospectus exteriores interioresque: a celebrioribus\
    \ architectis inventi: nunc tandem suis cum plantis ac mensuris."
  via_readux: true
tagline: an annotated digital edition
title: "Insignium Rom\xE6 templorum prospectus exteriores interioresque: a celebrioribus\
  \ architectis inventi: nunc tandem suis cum plantis ac mensuris."
url: https://jcmundy.github.io
version: 0.7
